export type { TheoLink, TheoRoute, RouteMatch, FormalityLevel } from "./types"
export { THEO_ROUTES, FALLBACK_ROUTE } from "./routes"
export { normalize, tokenize } from "./text"
export { levenshtein, isCloseMatch } from "./fuzzy"
export { STOPWORDS } from "./stopwords"
export { scoreRoute, findBestMatch, findTopMatches } from "./matcher"
export { detectFormality } from "./formality"
